### PR TITLE
Tao Responsive 9-14

### PR DESCRIPTION
**Pull request by linhpduong**
https://edu-redmine.sun-asterisk.vn/issues/35664

Screen Shot 2021-04-20 at 09 54 27
Screen Shot 2021-04-20 at 10 05 15
Screen Shot 2021-04-20 at 10 16 18
Screen Shot 2021-04-20 at 10 23 43

### CODE REVIEW

**Comment by linhpduong** [comment]
ready

**Comment by linhpduong** [comment]
ready

**Comment by manhnt-0960** [comment]
commented

**Comment by linhpduong** [comment]
ready

**Pull request merged**
